### ISSUE TITLE
Unreasonable compare result

### ISSUE THREAD

**Issue by chihsuanwu** [Pin-Yen/EarthMover#4]
When comparing two versions, most of the results are tie.
![2017-09-15 1](https://user-images.githubusercontent.com/22000682/30510320-69f795cc-9af4-11e7-99c4-06517d70fb5f.png)
![2017-09-15](https://user-images.githubusercontent.com/22000682/30510322-6f775abe-9af4-11e7-8f50-ba5dbabe2a5e.png)

**Comment by Pin-Yen** [comment]
@chihsuanwu 
I found an bug when investigating this issue, but there must be other major bugs.
compare( ) in [compare.py](https://github.com/Pin-Yen/EarthMover/blob/master/compare/compare.py) posts a play request with row=-1, col=-1 when the opponent passes. Instead it should request '/pass'.
But this bug has no reason to alter the tie count significantly.

**Comment by Pin-Yen** [comment]
@Pin-Yen
test

**Comment by chihsuanwu** [comment]
I tested a very extreme situation, but still the same result.
Level 0 only simulated 100 times, and level 2 unchanged.
![image](https://user-images.githubusercontent.com/22000682/30510672-db72c964-9afa-11e7-9296-c2a324a5bd79.png)

**Comment by chihsuanwu** [comment]
It's strange that it seems to continue pass many times
![image](https://user-images.githubusercontent.com/22000682/30510762-9904398a-9afc-11e7-9fd9-167a43a6b2c3.png)

**Comment by Pin-Yen** [comment]
Looks like I forgot to request ```/start``` (reintiailize EM) before each new round .....
